export const patients = [
  {
    name: 'Lainie',
    image: '../images/testimonials/laniepurple.png',
    duration: '20 months',
  },
  {
    name: 'Ron L.',
    image: '../images/testimonials/Ron_Lucien.jpg',
    duration: 'INVISALIGN',
  },
  {
    name: 'Elizabeth',
    image: '../images/testimonials/elizabethpatient.jpeg',
    duration: 'INVISALIGN, GROWTH APPLIANCE',
  },
  {
    name: 'Kinzie',
    image: '../images/testimonials/kinzie1.jpg',
    duration: 'BRACES, 24 months',
  },
  { name: 'Kasprenski',
    image: '../images/testimonials/kasprenski.jpg',
    duration: '--',
  },
  {
    name: 'Leanne',
    image: '../images/testimonials/leanne.png',
    duration: '12 months',
  },
  {
    name: 'Harold',
    image: '../images/testimonials/Narvaez.jpg',
    duration: 'Invisalign',
  },
  { name: 'Rosie & Grace',
    image: '../images/testimonials/Rosiegrace.png',
    duration: '--',
  },
  {
    name: 'Keith',
    image: '../images/testimonials/hobsonblue.png',
    duration: '--',
  },
  {
    name: 'Justin',
    image: '../images/testimonials/hurlburt.jpeg',
    duration: 'Invisalign, 2 years',
  },
  { name: 'Kara',
    image: '../images/testimonials/Kara.jpeg',
    duration: '--',
  },
  {
    name: 'Sophia',
    image: '../images/testimonials/Sophia_Lee.jpg',
    duration: '2 years, Braces',
  },
  { name: 'Brynn',
    image: '../images/testimonials/brynnportrait.png',
    duration: '--',
  },
  { name: 'Emma',
    image: '../images/testimonials/Emma.png',
    duration: '--',
  },
  {
    name: 'Brooke',
    image: '../images/testimonials/Brooke_Walker.jpg',
    duration: '2 years, Braces',
  },
  {
    name: 'Nilaya',
    image: '../images/testimonials/nilaya.jpeg',
    duration: 'Braces',
  },
  { name: 'Maria A.',
    image: '../images/testimonials/Maria_Anagnostou.jpg',
    duration: '--',
  },
  {
    name: 'Natasha K.',
    image: '../images/testimonials/Natasha_Khela.jpg',
    duration: '--',
  },
  {
    name: 'James C.',
    image: '../images/testimonials/James_Cipolla.jpg',
    duration: 'Invisalign, 2 years',
  },
  {
    name: 'Devika K.',
    image: '../images/testimonials/Devika_Knafo.jpg',
    duration: '--',
  },
  {
    name: 'Ibis S.',
    image: '../images/testimonials/Ibis_Subero.jpg',
    duration: 'Invisalign, 1 year',
  },
  { name: 'Abigail',
    image: '../images/testimonials/abigail.png',
    duration: '--',
  },
  { name: 'Emma',
    image: '../images/testimonials/EmmaF.png',
    duration: '--',
  },
  {
    name: 'Karoun G',
    image: '../images/test/base.jpg',
    duration: 'Motion Appliance, Invisalign',
  },
]