import './globals.css'
import "@/public/styles/uploadthing.css"
import "@/public/styles/index.css"
import { auth } from '@/server/auth'
import App from './app'


export const metadata = {
  title: {
    template: '%s | Create Next App',
    default: 'Create Next App',
  },
  description: 'Generated by create next app',
}


export default async function RootLayout({ children }) {
  const session = await auth()

  return (
    <html lang="en">
      <body suppressHydrationWarning>
        <App user={session?.user}>
          {children}
        </App>
           <div id="modal-root"></div>
      </body>
    </html>
  )
}
