import type { Metadata } from "next";
import React from "react";
import "./globals.css";
import Logo from "@/components/logo";
import { BannerMarquee } from "@/components/banner-marquee";
import { Toaster } from "@/components/ui/sonner";

export const metadata: Metadata = {
  title: {
    template: "%s | FreySmiles",
    default: "FreySmiles",
  },
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="./icon.svg" type="image/svg+xml" />
      </head>
      <body suppressHydrationWarning>
        <Logo className="absolute top-12 left-5 h-6 w-auto fill-zinc-50/80 z-[999] xl:h-7" />
        <main>
          <BannerMarquee />
          {children}
        </main>
        <div id="modal-root" />
        <Toaster />
      </body>
    </html>
  );
}
